name: MERN CD

on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
           cd jvlcode_todo_list_project/ 
           ls
           pwd
           ls -la
           whoami
           cat frontend/.env.prod
           cat backend/.env.prod
           cat backend/seedTasksData.js
           docker stop $(docker ps -aq) 2>/dev/null || true
           docker rm $(docker ps -aq) 2>/dev/null || true
           docker rmi $(docker images -q) -f 2>/dev/null || true
           docker compose down
           docker compose up --build