name: MERN CD

on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
           cd jvlcode_todo_list_project/ 
            rm -rf *
            # Pull fresh code from Git
            git reset --hard
            git clean -fd
           git pull origin main
           docker compose down
           docker compose up --build -d