name: MERN CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd jvlcode_todo_list_project/

            # Delete all files except .git
            find . -mindepth 1 ! -name ".git" -delete

            # Pull latest code
            git reset --hard
            git clean -fd
            git pull origin main

            # Rebuild Docker containers
            docker compose down
            docker compose up --build -d
EOF
