name: MERN CD

on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            whoami
            sudo cd /home/ec2-user/jvlcode_todo_list_project/
            sudo docker compose down
            sudo docker compose up --build -d
            whoami
            pwd
            sudo docker images
            echo "sudo docker images"
            echo "--------------------------"
            sudo docker ps 
            echo " sudo docker ps"
            echo "--------------------------"
            sudo docker ps -a