name: MERN CD

on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.4.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd jvlcode_todo_list_project/
            
            # Remove all files except .git
            find . -mindepth 1 ! -name ".git" -delete
            
            # Pull fresh code from Git
            git reset --hard
            git clean -fd
            git pull origin main
            
            # Rebuild containers
            docker compose down
            docker compose up --build -d